### ISSUE TITLE
Tracking issue for libz blitz evaluation of same-file

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#15]
This is the tracking issue for the evaluation performed by the community over the last few weeks.

- [x] [Do a pass over documentation](https://github.com/BurntSushi/same-file/issues/28)
- [x] [Clarify Approach to comparing files in docs](https://github.com/BurntSushi/same-file/issues/2)
- [x] [Add examples to public methods on `Handle`](https://github.com/BurntSushi/same-file/issues/3)
- [x] [Add Errors Section to methods on `Handle`](https://github.com/BurntSushi/same-file/issues/4)
- [x] [Add Errors Section to `same_file` method](https://github.com/BurntSushi/same-file/issues/5)
- [x] [Replace `try!` with `?` in examples](https://github.com/BurntSushi/same-file/issues/6)
- [x] [Note why `Handle` methods in `unix` won't panic](https://github.com/BurntSushi/same-file/issues/7)
- [x] [Note why `Handle` methods in `win` won't panic](https://github.com/BurntSushi/same-file/issues/8)
- [x] [Add hyperlinks to items in docs prose](https://github.com/BurntSushi/same-file/issues/9)
- [x] [Implement `Hash` for `Handle`](https://github.com/BurntSushi/same-file/issues/10)
- [x] [Ensure `Handle` is `Send + Sync`](https://github.com/BurntSushi/same-file/issues/11)
- [x] [Add `html_root` attribute](https://github.com/BurntSushi/same-file/issues/12)
- [x] [Note that `dev` and `ino` methods are unix only](https://github.com/BurntSushi/same-file/issues/14)

Also part of the libz blitz but not really a contribution opportunity:

- [x] [Start tracking release notes for version bumps](https://github.com/BurntSushi/same-file/issues/13)

**Comment by yandexx** [comment]
Hi! I'll try to tackle #3, #4, #5, #6, #9 for now if that's OK.

**Comment by brson** [comment]
@yandexx Go for it :)

**Comment by gurgalex** [comment]
Has #14 already been taken?

**Comment by yandexx** [comment]
@gurgalex No, nobody's taken it, so go for it!

**Comment by KodrAus** [comment]
Ok so we've just got the one contribution issue left, which is https://github.com/BurntSushi/same-file/issues/2. Thanks everyone who's contributed so far! :tada:

**Comment by KodrAus** [comment]
I've added a new issue for running over the documentation and making sure it all flows nicely.

**Comment by BurntSushi** [comment]
Thanks @KodrAus! I'll submit a PR shortly with some minor tweaks and then we can get this to 1.0! :tada:
